name: cyber_risk_dbt
version: "1.0.0"
config-version: 2

profile: cyber_risk_dbt

model-paths:
  - models

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  cyber_risk_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
